apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: app-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.99-192.168.1.100
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: app-adv
  namespace: metallb-system
