apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server
  namespace: mohammad-ullah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      containers:
        - name: ostad-server
          image: aureri/ostad-server
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: mongo-config
