apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-ui
  namespace: mohammad-ullah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-ui
  template:
    metadata:
      labels:
        app: ostad-ui
    spec:
      containers:
        - name: ostad-ui
          image: aureri/ostad-ui
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: vite-config
                  key: VITE_API_HOST
            - name: VITE_API_PORT
              valueFrom:
                configMapKeyRef:
                  name: vite-config
                  key: VITE_API_PORT
