# Default values for ostad-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mongo:
  nameOverride: "mongo"
  fullnameOverride: "mongo"
  image:
    repository: mongo
    tag: "latest"
  service:
    type: ClusterIP
    port: 27017
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 256Mi
  volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: mongo-pvc
  volumeMounts:
    - name: mongo-persistent-storage
      mountPath: /data/db
  env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: MONGO_USER
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: MONGO_PASS

mongo-express:
  nameOverride: "mongo-express"
  fullnameOverride: "mongo-express"
  image:
    repository: mongo-express
    tag: "latest"
  service:
    type: NodePort
    port: 8081
    nodePort: 30090
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: MONGO_USER
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: MONGO_PASS
    - name: ME_CONFIG_MONGODB_SERVER
      valueFrom:
        configMapKeyRef:
          name: mongo-config
          key: MONGO_SERVER
    - name: ME_CONFIG_SITE_BASEURL
      valueFrom:
        configMapKeyRef:
          name: mongo-config
          key: ME_BASEURL

ostad-server:
  nameOverride: "ostad-server"
  fullnameOverride: "ostad-server"
  image:
    repository: aureri/ostad-server
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 5050
    nodePort: 30070
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envFrom:
    - configMapRef:
        name: mongo-config

ostad-ui:
  nameOverride: "ostad-ui"
  fullnameOverride: "ostad-ui"
  image:
    repository: aureri/ostad-ui
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 5173
    nodePort: 30060
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: VITE_API_HOST
      valueFrom:
        configMapKeyRef:
          name: vite-config
          key: VITE_API_HOST
    - name: VITE_API_PORT
      valueFrom:
        configMapKeyRef:
          name: vite-config
          key: VITE_API_PORT
