apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mohammad-ullah
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
