apiVersion: v1
kind: Service
metadata:
  name: ostad-server
  namespace: mohammad-ullah
spec:
  selector:
    app: ostad-server
  type: ClusterIP
  ports:
    - name: ostad-server
      protocol: TCP
      port: 8000
      targetPort: 8000
