apiVersion: v1
kind: Service
metadata:
  name: ostad-ui
  namespace: mohammad-ullah
spec:
  selector:
    app: ostad-ui
  type: NodePort
  ports:
    - name: ostad-ui
      protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30000
